# Generated by Django 3.1.4 on 2021-03-03 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='MallOwnerShopOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mallOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_owner_foreign_key', to=settings.AUTH_USER_MODEL)),
                ('shopOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner_foreign_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Mall Owner and Shop Owner's relation key",
                'verbose_name_plural': "Mall Owner and Shop Owner's relation keys",
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('date', models.DateTimeField(blank=True)),
                ('imageTitle', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageDetails', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc14.images')),
            ],
            options={
                'verbose_name': 'Image Detail',
                'verbose_name_plural': 'Images Details',
            },
        ),
        migrations.CreateModel(
            name='DetectionVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='videos/detections/')),
                ('thumbnail', models.FileField(upload_to='videos/detections/thumbnails/')),
                ('date', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Video',
                'verbose_name_plural': 'Detection Videos',
            },
        ),
    ]
