# Generated by Django 3.1.4 on 2021-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionvideos',
            name='average_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionvideos',
            name='max_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionvideos',
            name='median_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionvideos',
            name='min_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
