# Generated by Django 3.1.4 on 2021-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
