# Generated by Django 3.1.4 on 2021-02-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0003_auto_20210206_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageDetails', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccc14.images')),
            ],
            options={
                'verbose_name': 'Image Detail',
                'verbose_name_plural': 'Images Details',
            },
        ),
    ]
