# Generated by Django 3.1.4 on 2021-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0005_detectionvideos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionvideos',
            options={'verbose_name': 'Detection Video', 'verbose_name_plural': 'Detection Videos'},
        ),
        migrations.AddField(
            model_name='detectionvideos',
            name='thumbnail',
            field=models.FileField(default=None, upload_to='videos/detections/thumbnails/'),
            preserve_default=False,
        ),
    ]
