# Generated by Django 3.1.4 on 2021-02-07 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0006_auto_20210207_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionvideos',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
