# Generated by Django 3.1.4 on 2021-02-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0007_detectionvideos_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
