# Generated by Django 3.1.4 on 2021-02-21 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0008_images_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='date',
        ),
        migrations.AddField(
            model_name='images',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
