# Generated by Django 3.1.4 on 2021-02-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0009_auto_20210221_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
