# Generated by Django 3.1.4 on 2021-02-23 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ccc14', '0011_auto_20210222_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionvideos',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='detectionvideos',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
